sudo: required
services:
  - docker
os:
  - linux

language: node_js
node_js:
  - "10"
  - "12"
  - "14"

before_script:
  - npm run run-container
  - sleep 10

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

after_script:
  - npm run remove-container
